#ifndef CN_RES_H
#define CN_RES_H
//---------------------------------------------------------------------------
//---jinggy---2004-11-19--聖戰---begin
#define STR_FIGHTER_EUDEMON_NAME            "狂暴 ·巴芬亞" //tcp2005.9.13 add
#define STR_MAGICIAN_EUDEMON_NAME           "暗夜·提拉克"  //tcp2005.9.13 add
#define STR_GHOSTLEVEL_EUDEMON_NOTCOMPETENT	"★ 升級裝備魔魂等級失敗，幻獸不符合條件！★"
#define STR_GHOSTLEVEL_SUCCESS				"★ 升級裝備魔魂等級成功，恭喜你！希望繼續努力！★"
#define STR_GHOSTLEVEL_FAILED				"★ 升級裝備魔魂等級失敗，這次你的運氣不是很好，請再接再厲！★"
#define STR_GHOSTLEVEL_FAILED_NOTYPE		"★ 沒有對應的數據！★"

#define STR_EMBED_SUCC	"嵌入成功！"
#define STR_EMBED_FAIL	"嵌入失敗！"
#define STR_UPEQUIPLEVEL_FAIL_NOTYPE		"★ 升級裝備等級失敗！沒有對應的設備！★"
#define STR_UPEQUIPLEVEL_FAIL				"★ 升級裝備等級失敗！★"
#define STR_UPEQUIPLEVEL_SUCC				"★ 升級裝備等級成功！★"

#define STR_UPEQUIPLEVE_SUCC				"★ 升級裝備的等級成功，恭喜你！希望繼續努力！★"
#define STR_UPEQUIPLEVE_FAIL				"★ 升級裝備的等級失敗，這次你的運氣不是很好，請再接再厲！★"

//狀態攻擊類1---10-GEM  升級技能
#define STR_GEMSKILL_FORGE_SUCCESS			"★ 狀態攻擊類寶石打造成功，恭喜你！繼續努力啊！★"

#define STR_QUALITY_UPGRADE_SUCCESS         "★ 升級裝備品質成功，恭喜你！繼續努力啊！★"
#define STR_QUALITY_UPGRADE_FAILED          "★ 升級裝備品質失敗，這次你的運氣不是很好，請再接再厲！★"
#define STR_QUALITY_UPGRADE_MAXLEVEL        "★ 升級裝備品質失敗，你的裝備已經是最高品質了！★"
#define STR_QUALITY_ADD_HOLE                "★ 恭喜你，設備上加了個洞，此洞可以用於鑲嵌寶石！★"//tcp2005.9.15 add
#define STR_QUALITY_EUDEMON_ATTACK          "★ 恭喜閣下，您的武器獲得額外屬性，%s增強效果%d！★"//tcp2005.9.15 add
#define STR_EUDEMON_ATTACK1                  "地攻擊"//tcp2005.9.15 add
#define STR_EUDEMON_ATTACK2                  "水攻擊"//tcp2005.9.15 add
#define STR_EUDEMON_ATTACK3                  "火攻擊"//tcp2005.9.15 add
#define STR_EUDEMON_ATTACK4                  "風攻擊"//tcp2005.9.15 add


#define STR_ITEM_CHANGETYPE_FAILED          "★ 升級裝備品質失敗，沒有對應的類型！★"
#define STR_ITEM_CHANGEADDITION_FAILED      "★ 追加裝備屬性失敗，沒有對應的類型 ★"

#define STR_SYN_CANNOT_UPMEMBERLEVEL        "升級幫派成員等級失敗，你的條件還不符合！"
#define STR_SYN_SUCCESS_UPMEMBERLEVEL        "升級幫派成員等級成功，希望再接再厲！"

#define STR_SYN_APPLYATTACKSYN_SUCCESS        "申請攻打該城市成功，請三日後來攻城！"
#define STR_SYN_APPLYATTACKSYN_FAIL          "申請攻打該城市成功失敗，閣下的幫派條件不符合！"
#define STR_SYN_APPLYATTACKSYN_HASBEENAPPLIED "申請攻打該城市成功失敗，已經有人申請攻打了！"

#define STR_SYN_APPLYKICKOUT_MEMBER         "已經向幫主發出開除請求！"

#define STR_SYN_SETSUBLEADER_NOPROFFER		"不能設置，貢獻度不足！"
#define STR_SYN_APPLY_JOIN_FAILED			"請找團長或副團長加入！"
#define STR_SYN_NOTENOUGH_PROFFER_LEAVE		"您的軍團貢獻度小於%d，不允許退團！"
#define STR_SYN_LEAVE_s						"%s 退出了軍團！"

#define STR_ACTION_USER_FLYTOMAINMAP_ERROR	"主地圖不存在，回城卷無法使用！"
#define STR_ACTION_IDENT_SUCC				"鑒定成功！"
#define STR_ACTION_IDENT_FAIL				"鑒定失敗！"
#define STR_ACTION_IDENT_FAIL_DISAPPEAR		"鑒定失敗，物品已損壞！"

#define STR_SYN_SETDRESS_SUCC				"設置幫派服裝成功！"
#define STR_SYN_PUTONDESS_ERR				"必須是團長才能下穿幫派服裝的命令！"
#define STR_SYN_CREATESUBSUB_ERR			"不符合條件或分隊已經滿了！"
#define STR_SYN_DEMISE_SUCC					"您將團長職位禪讓給了%s"
#define STR_SYN_DEMISE_CON					"恭喜您成為了%s軍團團長"
#define STR_SYN_DEMISE_PROMPT				"%s出任%s軍團團長一職"
#define STR_SYN_SETSUBLEADER_ERR			"%s等級不足或對軍團的貢獻不夠，不能出任該職務。"

#define STR_SYN_SETSUBLEADER_SUCC			"您冊封了%s為%s分團副團長一職"
#define STR_SYN_SETSUBLEADER_CON			"恭喜您成為了%s分團副團長"
#define STR_SYN_SETSUBLEADER_PROMPT			"%s出任%s分團副團長一職"

#define STR_SYN_SETSUBSUBLEADER_SUCC		"您冊封了%s為%s分隊隊長一職"
#define STR_SYN_SETSUBSUBLEADER_CON			"恭喜您成為了%s分隊隊長"
#define STR_SYN_SETSUBSUBLEADER_PROMPT		"%s出任%s分隊隊長一職"
#define STR_SYN_CREATE_SUBSUBSYN_ERROR		"創建分隊，必須是分團的團長！"

//鑒定
#define STR_IDENT_NORMAL					"鑒定成功，得到%s"
#define STR_IDENT_QUALITY_ONE				"鑒定成功，得到良品 %s"
#define STR_IDENT_QUALITY_TWO				"鑒定成功，得到上品 %s"
#define STR_IDENT_QUALITY_THREE				"鑒定成功，得到精品 %s"
#define STR_IDENT_QUALITY_FOUR				"鑒定成功，得到極品 %s"

//聊天室
#define STR_CHATROOM_NAME								"聊天室%d"
#define STR_CHATROOM_CANNOT_INMOREROOM					"不能同時進入多個聊天室！"
#define STR_CHATROOM_CANNOT_INMOREROOM_FORNOMONEY		"金錢不夠，不能進入聊天室！"
#define STR_CHATROOM_WELCOME							"%s，歡迎閣下光臨 %s 聊天室，本聊天是管理員為%s"
#define STR_CHATROOM_LEAVE								"%s 離開了 %s 聊天室！"
#define STR_CHATROOM_CANAPPLYMANAGER					"管理員%s在規定時間內沒有上線。允許玩家申請成為管理員！"
#define STR_CHATROOM_MEMBERFULL							"本聊天室人員已經滿了！"
#define STR_CHATROOM_ROOMFEE_MODIFY						"當前聊天室費用已經更改，為%d金幣"

#define STR_DROPITEM_PROMPT				"您丟棄了%s ！"
#define STR_NOTIFYFRIEND_USERLEAVEMAP	"%s離開遊戲！"
#define STR_NOTIFYFRIEND_USERENTERMAP	"%s進入遊戲！"
//---jinggy---2004-11-19--聖戰---end
#define	STR_DOUBLE_MANTLE_FLAG		"此團標已經有人使用過了，請重新選擇團標。"
#define	STR_SETLOCK					"setlock"
#define	STR_UNLOCK					"unlock"
#define	STR_CLEARLOCK				"clearlock"
#define	STR_SETLOCK_HELP			"設置「保護鎖」密碼之前不能有舊的密碼，密碼必須為 6 ~ 9 位整數，不能使用字母或符號，也不能使用過於簡單的密碼。使用方法：/setlock 密碼"
#define	STR_UNLOCK_HELP				"臨時打開「保護鎖」，下線會自動加鎖。使用方法：/unlock 密碼"
#define	STR_CLEARLOCK_HELP			"永久清除「保護鎖」密碼。使用方法：/clearlock 舊密碼"
#define	STR_SETLOCK_OK				"已設置「保護鎖」的密碼。可使用「/unlock 密碼」臨時打開保護鎖，也可使用「/clearlock 舊密碼」永久清除保護鎖。"
#define	STR_SETLOCK_FAIL			"設置「保護鎖」失敗! 設密碼之前不能有舊的密碼，密碼必須為 6 ~ 9 位整數，不能使用字母或符號，也不能使用過於簡單的密碼。"
#define	STR_UNLOCK_OK				"已打開「保護鎖」，下線後會自動加鎖。"
#define	STR_CLEARLOCK_OK			"已永久清除「保護鎖」，該帳號不再受到「保護鎖」的保護。如需重新設置保護鎖，請使用「/setlock 密碼」。"
#define	STR_LOCKKEY_DENY			"請先打開「保護鎖」。使用方法：/unlock 密碼"
#define STR_SUPER_ATK_ADD			"技能啟動：%d秒內攻擊力增加%d。"
#define STR_SUPER_DEF_ADD			"技能啟動：%d秒內防禦力增加%d。"
#define STR_SUPER_MATK_ADD			"技能啟動：%d秒內魔法攻擊力增加%d。"
#define STR_SUPER_MDEF_ADD			"技能啟動：%d秒內魔法防禦力增加%d。"
#define	STRING_BET_WIN				"%s紅光滿面，雙眉帶彩，玩骰子贏了%d金幣！"
#define	STR_AWARD_VIRTUE_su			"%s得到功德值%u。"
#define	STR_SYNDICATE_LEADER		"騎士團團長"
#define	STR_SYNDICATE_LEADER2		"騎士團副團長"
#define	STR_SYNDICATE_LEADER3		"近衛團團長"
#define	STR_SYNDICATE_LEADER4		"近衛團副團長"
#define	STR_SYNDICATE_LEADER5		"近衛團代團長"
#define	STR_SYNDICATE_MEMBER		"騎士"
#define	STR_ERROR					"錯誤"
#define	STR_DELETE_FAILED			"刪除失敗!"
#define	STR_YOUR_CANNOT_WALK		"您不能走！"
#define	STR_TOP_LIST_dsd			"第%d名：%s(%d)"
#define	STR_INC_MOUNT_INTIMACY		"您的坐騎的親密度增加了。"
#define	STR_DEC_MOUNT_INTIMACY		"您的坐騎的親密度下降了。"
#define	STR_KICKOUT_ALL_AFTER		"開始處理kickoutall，服務器禁止登錄。%d秒之後，所有玩家退出。"
#define	STR_KICKOUT_ALL				"開始處理kickoutall，服務器禁止登錄，所有玩家退出中 . . ."
#define	STR_LOGIN_ANOTHER			"有人正在登陸此帳號。"
#define	STR_LOGIN_AGAIN				"此帳號已經有人登陸。"
#define	STR_KO_LIST_TITLE			"名次  姓名           數量"
#define	STR_TEAM_MONEY_s			"撿錢開關 %s"
#define	STR_TEAM_ITEM_s				"撿物品開關 %s"
#define STR_TEAM_GEM_s				"撿寶石開關 %s"
#define	STR_OPEN					"開"
#define	STR_CLOSE					"關"
#define STR_NOT_DISCARDABLE			"此物品不能丟棄。"
#define STR_NOT_SELL_ENABLE			"此物品不能出售。"
#define STR_NEXT_PAGE				"下一頁"
#define STR_CLOSE_BUTTON			"關閉"
#define STR_TOO_LOWER_SYN_MONEY		"騎士團基金不足，該功能已關閉。"
#define STR_SYN_AMOUNT_LIMIT        "騎士團人員不足，即將被強制解散，請盡快補充人員"
#define STR_SYN_MONEY_LIMIT         "騎士團資金不足，即將被強制解散，請盡快補充資金"
#define	STR_APPLY_ALLY_FAILED		"雙方必須是騎士團團長!"
#define STR_HITRATE_ADD				"技能啟動：%d秒內命中率增加%d倍。"
#define STR_DEFENCE_ADD				"技能啟動：%d秒內防禦力增加%d倍。"
#define STR_ATTACK_ADD				"技能啟動：%d秒內攻擊力增加%d倍。"
#define STR_HITRATE_ADD2			"技能啟動：%d秒內命中率增加%d。"
#define STR_DEFENCE_ADD2			"技能啟動：%d秒內防禦力增加%d。"
#define STR_ATTACK_ADD2				"技能啟動：%d秒內攻擊力增加%d。"
#define EXPLOST_PAYBY_SYNFUND		"騎士團基金抵消經驗損失%u。"
#define MALE_MATE_LOGIN				"您的先生來了"
#define FEMALE_MATE_LOGIN			"您的夫人來了"
#define NOMATE_NAME					"無"
#define TITILE_NONE					"無"
#define SYNNAME_NONE				"無"
#define	ACTIONSTR_NONE				"無"
#define	STR_DESTROY_SYNDICATE_SOON	"貴騎士團因騎士團基金耗盡，即將被系統強行解散。請及時補充騎士團基金。"
#define	STR_TARGET_OFFLINE			"對方不在線。"
#define	STR_SYNDICATE_COMBINESUB_ss	"騎士團 %s 被 % 吞併了。"
#define	STR_NEXTEQP_OVERLEV			"下一個等級的裝備已經超出閣下當前等級！"
#define	STR_BOOTH_BUY_sds			"%s 花了 %d 金幣購買你的%s。"
#define	STR_DISABLE_LAY_SYNTRANS	"該地圖禁止放置此類NPC!"
#define	STR_ITEM_LEV_TOO_HIGH		"裝備需求等級太高!"
#define	STR_TEAM_HUNT				"%s做惡多端，終於被以%s為首的緝捕隊伍抓獲!"
#define	STR_FOND_WANTED				"發現懸賞目標【%s】！"
#define	STR_FOND_POLICEWANTED		"發現官方懸賞目標【%s】！"
#define	STR_CANT_STORAGE			"該物品不能存放!"
#define	STR_SYN_FULL				"錯誤：騎士團人數已滿!"
#define	STR_JOIN_SYN_FAILED			"錯誤：加入失敗!"
#define	STR_INVALID_PET_NAME		"錯誤：不允許的名字!"
#define STR_JOIN_SYN_s				"恭喜您成為 %s 軍團團員。"
#define STR_SYN_NOTIFY_JOIN_s		"號外！號外！%s 加入了軍團。"
#define	STR_KICKOUT_MEMBER_s		"%s被開除出了%s軍團。"
#define	STR_KICKOUT_ME_s			"你被%s從騎士團中開除。"
#define STR_SYN_ALLY_s				"恭喜 %s 軍團與 %s 軍團結為兄弟軍團。"
#define STR_SYN_CLEAR_ALLY1_s		"與 %s 軍團解除盟友之約。"
#define STR_SYN_CLEAR_ALLY2_s		"%s 軍團與您的軍團解除盟友之約！"
#define STR_SYN_ENEMY_s				"%s 軍團將您的軍團列為敵對軍團。"
#define STR_SYN_CLEAR_ENEMY_s		"%s 軍團將與您的軍團解除敵對狀態。"
#define	STR_NO_BONUS				"抱歉，沒有獎品或者獎品 或 沒有經過領獎網頁確認。"
#define	STR_WARNING_CRASH			"注意：此命令只用於本地測試，否則可能導致服務器崩潰!"
#define	STR_CAN_STAND				"目標點不能落腳!"
#define	STR_SET_MAX_PLAYERS_u		"最大允許登錄人數改為: %u"
#define	STR_SHOW_PLAYERS_uu			"當前在線:%u, 最大在線:%u"
#define	STR_ARRESTMENT_PK_MODE		"捕殺PK模式，你可以攻擊怪物和黑名、藍名玩家，不會傷害到其它人。"
#define STR_SYNDICATE_PK_MODE       "騎士團PK模式，你可以PK所有除本團及同盟騎士團之外的玩家。"
#define	STR_TEAM_PK_MODE			"組隊PK模式，你可以攻擊怪物和其它人，不會傷害到自己和隊友。"
#define	STR_SAFE_PK_MODE			"安全PK模式，你只能攻擊怪物，不會傷害到其它任何玩家。"
#define	STR_FREE_PK_MODE			"自由PK模式，你可以攻擊任何人。"
#define	STR_NEED_PICK				"必須要裝備鋤頭才能挖礦。"
#define	STR_SYNDICATE_DESTROY_s		"%s 含淚解散了 %s 軍團。"
#define	STR_SYNDICATE_CREATE_ss		"恭喜 %s 騎士團創建%s成功。 "
#define	STR_SYN_LEADER_LOSE_uss		"騎士團[%u][%s]騎士團長失蹤，玩家[%s]暫代騎士團長之職。"
#define	STR_DONATE_ssd				"%s 捐贈 %u 金幣，用於軍團的建設！"
#define	STR_SYN_WAR_END				"城堡攻防戰結束!"
#define	STR_SYN_WAR_START			"城堡攻防戰開始!"
#define	STR_GOT_WIN_s				"%s獲得勝利!"
#define	STR_ERROR_DUPLICATE_NAME	"錯誤：人物已存在!"
#define	STR_ERROR_ILLEGAL_NAME		"錯誤：角色名不合法!"
#define	STR_ERROR_ILLEGAL_NAME2		"錯誤：名字不合法!"
#define	STR_ERROR_ILLEGAL_PASSWORD	"錯誤：密碼不合法!"
#define	STR_ERROR_ILLEGAL_ACCOUNT	"錯誤：帳號名不合法!"
#define	STR_ERROR_SERVER_FULL		"錯誤：服務器人數已滿，請稍後重新登錄!"
#define	STR_ERROR_LOWER_VERSION		"錯誤：版本號錯誤，請更新客戶端!"
#define	STR_ERROR_VERSION			"錯誤：版本號錯誤!"
#define	STR_FEW_FEE_NOTIFY			"您的包月卡將於 %s 到期，請及時充值。"
#define	STR_ACCOUNT_NOFEE			"您的帳號還沒有充值。"
#define	STR_LOGIN_ISP_FAIL			"登錄到ISP計費系統失敗。目前正在使用您自己的帳號進行計費。"
#define	STR_FEETYPE_KNOWN			"計費類型：未知。"
#define	STR_FEETYPE_HOUR			"計費類型：小時卡，剩餘小時數：%d.%d。"
#define	STR_FEETYPE_MONTH			"計費類型：包月卡。到期時間：%d年%d月%d日。"
#define	STR_FEETYPE_BARHOUR			"計費類型：網吧計點。"
#define	STR_FEETYPE_BARMONTH		"計費類型：網吧月卡。許可證數量%d。"
#define	STR_FEETYPE_ISP				"計費類型：ISP計費。"
#define	STR_FEETYPE_FREE			"計費類型：免費測試。"
#define	STR_SHUTDOWN_NOTIFY			"服務器維護，停機三十分鐘；請大家立即下線，避免數據丟失。"
#define	STR_NONSUCH_TRADE_sssu		"[交易] 極品交易，玩家[%s]給玩家[%s]物品[%s][%u]"
#define	STR_NOT_SO_MUCH_MONEY	    "您身上沒有這麼多錢！"
#define	STR_NOT_ENOUGH_MONEY	    "你的錢不足%d金幣!"
#define	STR_ATTACK_POLICE	        "閣下涉嫌襲警，請好自為之，以免惹火上身。"
#define	STR_KILLING_EXPERIENCE	    "獲擊殺額外經驗%u。"
#define	STR_KILLING_EXPEX			"獲低等級隊友獎勵和擊殺額外經驗%u。"
#define	STR_BAG_FULL	            "背包已滿!"
#define	STR_TRADE_SUCCEED	        "交易成功。"
#define	STR_TRADE_FAIL	            "交易失敗!"
#define	STR_USE_ITEM	            "您用掉了一件物品。"
#define	STR_INVALID_GUILD_NAME		"騎士團名字不合法!"
#define	STR_GUILD_FUND_NOT_ENOUGH	"騎士團基金不足%u金幣!"
#define	STR_NOT_AUTHORIZED	        "你沒有這個權力!"
#define	STR_ALLY_FULL	            "同盟表已滿!"
#define	STR_SYN_PLACE_FULL	        "該軍銜數量已滿!"
#define	STR_WANTED_ORDER	        "扣除定金%u金幣，取得%d號懸賞單，目標：%s，賞金：%u 金幣。"
#define	STR_WANTED_INFO				"據傳此人最近在【%s】一帶活動。"
#define	STR_INVALID_WANTED	        "錯誤的懸賞號！"
#define	STR_MAX_BONUTY				"賞金最大不能超過%d金幣！"
#define	STR_MIN_BONUTY				"賞金最少不能低於%d金幣！"
#define	STR_SUPERADD_BONUTY			"懸賞%u號賞金上升為%u金幣！"
#define	STR_LOWEST_SUPERADD_BONUTY	"最低添加懸賞額為%u金幣！"
#define	STR_CANCEL_WANTED			"懸賞%u號已經撤銷。"
#define	STR_NO_DISBAND	            "騎士團較大不宜解散，請選擇禪讓。"
#define	STR_PROTECTED_CODE	        "請先打開保護鎖。"
#define	STR_HIS_ALLY_FULL	        "對方的同盟表已滿!"
#define	STR_NOT_HERE	            "該玩家不在附近!"
#define	STR_CANNOT_RANK				"無法設置軍銜!"
#define	STR_NOT_ENOUGH_LEV			"你的等級不足%d級!"
#define	STR_LEVEL_NOT_ENOUGH	    "%s等級不足或對軍團的貢獻不夠，不能出任該職務!"
#define	STR_INVALID_NAME	        "名字不合法。"
#define	STR_INVALID_MSG	            "非法消息！"
#define	STR_MAGIC_FAILED            "魔法使用失敗！"
#define	STR_CANNOT_DEPOSIT	        "錯誤：此物品不宜存放!"
#define	STR_FORBIDDEN_GUILD_NAME	"您不能使用這個騎士團名。"
#define	STR_GUILD_INEXIST	        "該騎士團不存在。"
#define	STR_TEAM_EXPERIENCE	        "獲得了獎勵經驗%d"
#define	STR_TEAM_EXPEX				"獲得組隊和低等級隊友獎勵經驗%d"
#define	STR_LOST_EXPERIENCE	        "你損失了%d點經驗值!"
#define	STR_KILLING_TO_MUCH	        "殺人過多，將受到紅名的懲罰"
#define	STR_NOT_PK_MODE	            "當前模式下不能攻擊對方！"	
#define	STR_NOT_PK_EXP	            "經驗為負的情況下不能PK。"	
#define	STR_PK_FORBIDDEN	        "此處禁止毆鬥。"
#define	STR_MSG_SENT	   		    "留言成功，對方上線後就能看到你的留言。"	
#define	STR_MSG_FAILED				"每個好友留言間隔不能少於%d分鐘，留言失敗。"
#define	STR_INVALID_COORDINATE	    "非法坐標。"
#define	STR_GONE	                "走了"
#define	STR_JUMPED	                "跳了"
#define	STR_CONNECTION_OFF	        "客戶端網絡連接異常，系統自動關閉連接。"
#define	STR_WEAPON_SKILL_UP	        "恭喜閣下武器熟練度升級！"
#define	STR_FULLBAG_NO_MORE	        "閣下行囊已滿，無法放入更多物品。"
#define STR_ITEMBAG_FULL			"您的物品背包空間已滿，不能放置更多的物品。"
#define STR_GEMBAG_FULL				"您的寶石背包空間已滿，不能放置更多的物品。"
#define	STR_HEAVEY_BAG	            "閣下行囊過重，無法放入更多物品。"
#define	STR_ITEM_NOT_FOUND	        "物品找不到!"
#define	STR_ITEM_INEXIST	        "物品不存在!"
#define	STR_MONEYBAG_FULL	        "您的錢袋已滿!"
#define	STR_MAKE_ITEM_FAILED        "產生地圖物品[%u]失敗。"
#define	STR_MAKE_MONEY_FAILED	    "產生地圖金幣[%d]失敗。"
#define	STR_DAMAGED_REPAIR	        "%s即將損壞，請盡快修復，否則將徹底消失!"
#define	STR_DURABILITY_REPAIR	    "%s耐久度太低，請盡快修復，以免損傷。"
#define	STR_FAR_CANNOT_PICK	        "物品太遠，無法拾取。"
#define	STR_FULL_CANNOT_PICK	    "物品欄已滿，無法拾取物品。"
#define	STR_PICK_MONEY	            "撿到 %u 個金幣。"
#define	STR_FAILED_GENERATE_ITEM	"產生物品失敗。"
#define	STR_OTHERS_ITEM	            "別人的打的東西，暫時不能拾取!"	
#define	STR_GOT_ITEM	            "得到物品%s。"
#define	STR_GOT_IDENT_ITEM	        "得到未鑒定物品。"
#define	STR_DRAGONBALL	            "改良裝備輔助物品必須是【龍珠】。"
#define	STR_REPAIR_THEN_IMPROVE	    "改良裝備必須是修復好的物品。"
#define	STR_SUPERIOR_ALREADY	    "此裝備已經是極品了。"
#define	STR_CONNOT_IMPROVE	        "該裝備無法改良。"
#define	STR_METEOR	                "升級裝備的輔助物品必須是【流星】。"
#define	STR_REPAIR_THEN_UPGRADE	    "升級裝備必須是修復好的物品。"
#define	STR_UPGRADE_NOMORE	        "此裝備無法繼續升級！"
#define	STR_MINE_WITH_PECKER   	    "必須要裝備鋤頭才能挖礦。"
#define	STR_NO_MINE	                "此地沒有礦藏。"
#define	STR_GOLD_ORE	            "得到一個金礦石！"
#define	STR_EUXENITE_ORE	        "得到一個黑鐵礦！"
#define	STR_IRON_ORE	            "得到一個鐵礦石！"
#define	STR_COPPER_ORE	            "得到一個銅礦石！"
#define	STR_SILVER_ORE	            "得到一個銀礦石！"
#define	STR_GAIN_GEM	            "恭喜獲得一顆寶石！"
#define	STR_UNQUALIFIED	            "錯誤：條件檢查失敗！"
#define	STR_DIE	                    "您已經死了!"
#define	STR_DONOT_GIVE_UP	        "閣下身負重任，怎可自暴自棄？"	
#define	STR_CANNOT_JUMP	            "您不能跳！"
#define	STR_CHEAT	                "[作弊]你要分配的點數大於擁有的可分配點數。"
#define	STR_FRIEND_LIST_FULL	    "好友列表已滿。"
#define	STR_YOUR_FRIEND_ALREADY	    "對方已經是好友了。"
#define	STR_MAKE_FRIEND_SENT        "已經發送結為好友的請求"		
#define	STR_NOT_YOUR_FRIEND	        "%s 不是你的朋友。"
#define	STR_NEVER_PROPOSED	        "%s 沒有向你求過婚。"
#define	STR_SINGLE	                "您尚未，如何能夠離婚"
#define	STR_NOT_YOUR_SPOUSE	        "%s 和您並非夫妻關係。"
#define	STR_NOT_ENOUGH_MANA	        "您的魔力不足。"
#define	STR_UNABLE_USE_ITEM	        "無法使用物品!"
#define	STR_YOUR_BAG_FULL	        "物品欄已滿!"
#define	STR_SELFCARE			    "自顧身份。"
#define	STR_CAUTION					"小心為妙。"
#define	STR_BALANCED			    "勢均力敵。"
#define	STR_INVALID_AMOUNT	        "數量錯誤!"	
#define	STR_REPAIR_FAILED	        "不能修理!"
#define	STR_REPAIR_NO_MONEY_d	    "修理需要花費%d個金幣，金幣不足無法修理！"
#define	STR_INVALID_TITLE	        "錯誤：軍銜名不合法!"
#define	STR_NOT_FROM_YOUR_GUILD	    "對方不是您騎士團的成員。"
#define	STR_ITEM_DAMAGED	        "該物品損壞了!"
#define	STR_CHANGE_NAME	            "您已經更名為%s。"
#define	STR_INCREASE_MONEY	        "[您的錢增加了。]"
#define	STR_INCREASE_ITEM	        "[您的物品增加了。]"
#define	STR_KICKOUTALL	            "開始處理kickoutall，服務器禁止登錄，所有玩家退出中 . . ."	
#define	STR_ACTION_SEEN	            "可以顯示ACTION了。"
#define	STR_ACTION_NOTSEEN	        "不顯示ACTION了。"
#define	STR_NO_STOP	                "目標點不能落腳!"
#define	STR_LOCAL_TEST	            "注意：此命令只用於本地測試，否則可能導致服務器崩潰!"
#define	STR_ACTION_UPDATED	        "[ACTION 更新了。]"
#define	STR_KICK_OUT_GUILD	        "%s 已經被開除出騎士團！"
#define	STR_NO_PRIZE	            "抱歉，沒有獎品或者獎品 或 沒有經過領獎網頁確認。"
#define	STR_INVALID_CHARACTER	    "消息中包含非法字符!"
#define	STR_LOW_LEVEL	            "你的等級太低!"
#define	STR_GM_NO_TEAM	            "【GM】不能進行隊伍操作。"
#define	STR_TEAMMATE_CANNOT_CREATE	"[隊伍]您已經在隊伍中了，不能創建新隊伍。"
#define	STR_CREATE_TEAM_FAILED	    "[隊伍]您創建隊伍失敗。"
#define	STR_INTEAM_NOJOIN		    "[隊伍]您已經有隊伍了。不能申請加入新隊伍。"
#define	STR_NO_APPLICANT		    "[隊伍]沒有找到申請對象。"
#define	STR_NO_TEAM					"[隊伍]您所申請的對象沒有創建隊伍。"
#define	STR_FORBIDDEN_JOIN	        "[隊伍]對方隊伍禁止加入了。"
#define	STR_TEAM_FULL			    "[隊伍]您的所申請的隊伍人數已滿。"
#define	STR_NO_CAPTAIN_CLOSE	    "[隊伍]申請對像不是隊長，請向隊長提出申請。"
#define	STR_JOIN_REQUEST_SENT	    "[隊伍]已經發出加入隊伍請求。"
#define	STR_INVI_SENT			    "[隊伍]加入隊伍申請已經提交，請等待回應。"
#define	STR_NO_TEAM_TO_INVITE	    "[隊伍]您沒有隊伍，怎能接受別人加入隊伍？"
#define	STR_NOT_CAPTAIN_INVITE	    "[隊伍]您不是隊長，怎能接受別人加入隊伍？"
#define	STR_YOUR_TEAM_FULL		    "[隊伍]您的隊伍人數已滿。"
#define	STR_APPLICANT_NOT_FOUND	    "[隊伍]沒有找到發出申請的玩家。"
#define	STR_HAVE_JOIN_TEAM	        "[隊伍]您已經加入隊伍了，不能同時加入另外一個。"
#define	STR_NOT_TO_JOIN	            "[隊伍]對方沒有發出加入申請，您不能接受對方。"
#define	STR_NOTEAM_TO_INVITE	    "[隊伍]您沒有隊伍，怎能邀請別人加入隊伍？"
#define	STR_TEAM_CLOSED	            "[隊伍]您不允許其他人加入隊伍，操作失敗！"
#define	STR_NOT_CAPTAIN_ACCEPT	    "[隊伍]您不是隊長，怎能邀請別人加入隊伍？"
#define	STR_INVITED_NOT_FOUND	    "[隊伍]沒有找到要邀請的玩家。"
#define	STR_HAS_IN_TEAM	            "[隊伍]您所邀請的對象的已經有隊伍了。"
#define	STR_INVITE_SENT				"[隊伍]已經發出邀請加入隊伍請求。"
#define	STR_SENT_WAIT				"[隊伍]邀請已經發出，請等待。"
#define	STR_INTEAM_NOACCEPT			"[隊伍]您已經有隊伍了，不能接受邀請加入新隊伍。"
#define	STR_INVITER_NOT_FOUND	    "[隊伍]沒有找到邀請者。"
#define	STR_NOT_CREATE_TEAM		    "[隊伍]對方還沒有組隊。"
#define	STR_HIS_TEAM_FULL		    "[隊伍]對方的隊伍已經滿員了。"
#define	STR_NOT_BE_INVIITED	  	    "[隊伍]對方沒有向您發出加入隊伍的邀請，操作失敗。"
#define	STR_NO_TEAM_TO_LEAVE	    "[隊伍]您還不是隊員，不能退出隊伍。"
#define	STR_NO_TEAM_TO_DISMISS	    "[隊伍]您還沒有隊伍，不能解散隊伍。"
#define	STR_NOT_CAPTAIN_DISMISS	    "[隊伍]您不是隊長，不能解散隊伍。"
#define STR_INVITED_IS_DEAD			"[隊伍]不能邀請亡靈狀態下玩家加入隊伍。"
#define STR_APPLIED_LEADER_DEAD		"[隊伍]不能加入亡靈的隊伍。"
#define	STR_NO_TRADE_IN_BATTLE	    "錯誤：戰鬥中不能執行交易指令！"
#define	STR_NO_TRADE_IN_TEAM	    "錯誤：組隊狀態不能執行交易指令！"
#define	STR_NO_IN_TEAM				"[隊伍]您沒有隊伍。"	
#define	STR_NO_TRADE_TARGET	        "[交易]沒有找到交易對象。"	
#define	STR_TARGET_TRADING	        "[交易]對方正在交易中，請稍後再試!"
#define	STR_TRADING_REQEST_SENT	    "[交易]已經發出交易請求。"
#define	STR_NOT_FOR_TRADE	        "錯誤：不能交易此物品!"
#define	STR_CANNOT_GO				"您不能走！"
#define	STR_FREE_PK	                "自由PK模式，你可以攻擊任何人。"
#define	STR_PEACE	                "安全PK模式，你只能攻擊怪物，不會傷害到其它任何玩家。"
#define	STR_TEAM_PK	                "組隊PK模式，你可以攻擊怪物和其它人，不會傷害到自己和隊友。"
#define	STR_JOIN_A_GUILD	        "%s 加入了幫派。"
#define	STR_BONUS					"恭喜獲得%u個獎品，請去交易市場領獎處領獎！"
#define	STR_TO_MAKE_FRIEND			"血與火的洗禮證明了堅固的友誼，%s對你報以信任的眼神，你是否願意接受？"
#define	STR_MAKE_FRIEND				"%s、%s歃血為盟，宣誓從此將生死與共，永不背叛！"
#define	STR_BREAK_FRIEND			"%s 不齒 %s 的行徑，從此斷絕好友關係，兩不相干。"
#define	STR_MARRY					"%s 和 %s 在神的面前立下永不分離的誓言，從此結為夫妻。"
#define	STR_DIVORCE					"%s 和 %s 感情破裂，宣佈離婚！"
#define	STR_SYN_CONQUER				"【%s】經過激烈的嘶殺，終於贏得了戰爭的勝利"
#define	STR_POLICE_WANTED_ORDER		"揭榜確認：追捕目標%s，據傳此人最近在%s一帶出沒。"
#define	STR_GOTO_JAIL				"%s 殺人如麻，終於失手被擒，打入大牢。"

#define STR_STUDENT_FULL			"徒弟列表已滿。"
#define STR_YOUR_STUDENT_ALREADY	"對方已經是你的徒弟了。"
#define STR_STUDENT_APPLY			"%s 請求招你為徒弟。"
#define STR_STUDENT_APPLY_SENT		"招收徒弟的請求已發出。"
#define STR_HAVE_TEACHER_ALREADY	"對方已經有師傅了。"
#define STR_TEACHER_APPLY			"%s 請求拜你為師。"
#define STR_TEACHER_APPLY_SENT		"拜師的請求已發出。"
#define STR_NO_STUDENT_APPLY		"對方並沒有要求招你為徒。"
#define STR_NO_TEACHER_APPLY		"對方並沒有請求拜你為師。"
#define STR_MAKE_TEACHERSTUDENT		"%s 與 %s 建立了師徒關係。"
#define STR_TEACHER_EXP				"獲得導師經驗 %d。"
#define STR_NOT_ENOUGH_TUTOREXP		"導師經驗不足。"
#define STR_NOT_ENOUGH_TUTOREXP2	"對方導師經驗不足，申請失敗。"
#define STR_HEIGHT_LEV				"您的等級太高。"
#define STR_HEIGHT_LEV2				"對方等級太高。"
#define STR_LOW_LEV2				"對方等級太低，不允許向對方拜師。"
#define STR_STUDENT_FULL2			"對方徒弟名額已滿，申請失敗。"
#define STR_TUTOR_NO_ONLINE         "此導師不在線！"
#define STR_LEAVE_TEACHER			"您與 %s 解除了師徒關係。"
#define STR_LEAVE_TEACHER2			"%s 與你解除了師徒關係。"
#define STR_LEAVE_TEACHER3			"您的徒弟 %s 與您結束了師徒關係。"
#define STR_LEAVE_TEACHER4			"您的師傅 %s 與您結束了師徒關係。"

#define STR_MERCENARY_TASK_OK		"傭兵任務提交成功！"
#define STR_INVALID_MERCENARYTASK	"錯誤：非法傭兵任務！"
#define STR_PUBLISH_ONE_TASK_ONLY	"錯誤：一次只能發佈一條任務！"
#define STR_DUPLICATE_TASK			"錯誤：一次只能接一個任務！"
#define STR_TUTOR_REQUEST			"%s 請求拜你為師，請盡快跟他聯繫。"
#define STR_TUTOR_REQUEST_SEND   	"三分鐘內導師會跟您聯繫，如果三分鐘內沒有聯繫，則可另外拜師。"
#define STR_CANNOT_CANCEL_TASK		"錯誤：任務不能取消！"
#define STR_ACCEPT_TASK_OK			"接任務成功。"
#define STR_TAKE_PRIZE_OK			"成功領取獎品。"
#define STR_TASK_NOT_FINISHED_YET	"錯誤：任務還未完成。"
#define STR_CANCEL_TASK_OK			"任務成功取消。"
#define STR_CLOSE_TASK_OK			"任務成功結束。"
#define STR_TASK_FINISHED			"任務完成。"
#define STR_LOW_MERCENARY_RANK		"錯誤：傭兵等級太低。"
#define STR_TASK_TIMEOUT			"傭兵任務超時，已經自動取消。"
#define STR_DUPLICATE_ANNOUNCE      "一次只能發一個公告！"
#define STR_LOW_GRADE               "你的導師等級太低，不能發佈公告。"
#define STR_ANNOUNCE_SUCCEED        "發佈公告成功。"
#define STR_NO_ANNOUNCE             "你沒有發佈公告！"
#define STR_DELETE_ANNOUNCE         "成功刪除公告"
#define STR_ILLEGAL_TASK_ITEM		"物品不符合任務要求！"
#define STR_NOANY_ANNOUNCE          "當前沒有導師公告分佈"
#define STR_CANNOT_ACCEPT_MYTASK	"錯誤：不能接自己的任務！"
#define STR_EUDEMON_LOW_LEVEL		"錯誤：幻獸等級不足%d級！"
#define STR_EUDEMON_CANNOT_EVOLVE	"錯誤：幻獸不能進化！"
#define STR_AVOID_DEATH				"自動使用 %s 寶石，免死一次。"
#define STR_AUTO_USE_SCAPEGOAT		"自動使用 %s 寶石，免受懲罰。"
#define STR_AUTO_USE_REBORN			"自動使用 %s 寶石，原地復活。"
#define STR_AUTO_USE_ANTISTEAL		"自動使用 %s 寶石，免受偷盜。"
#define STR_AVOID_STEAL				"依靠反偷盜寶石的幫助，你躲過了%s的偷竊。"
#define STR_STOLEN					"你被%s偷走了%s。"
#define STR_AUCTION_PACKAGE_FULL    "你的拍賣倉庫已滿，請先取出裡面的物品，再加入拍賣物品"
#define STR_AUCTION_PACKAGE_FULL1   "你的拍賣倉庫已滿，不能參加競拍。"
#define STR_AUCTION_LESS_MONEY      "你沒有足夠的金錢支付拍賣佣金。"
#define STR_AUCTION_SYS_BID         "現在是系統拍賣時間，玩家拍賣在系統拍賣結束後重新開始"
#define STR_AUCTION_BID_PACKAGE_FULL "倉庫已滿，請待有空位的時候再放入競拍物品"
#define STR_NOT_SHOUT               "物品已經"
#define STR_SHOUT                   "您花了%d枚金幣參與%s的競拍。"
#define STR_AUCTION_JOIN_SUCCESS    "你的物品已經放入競拍倉庫等待拍賣。在隊列中的位置為%d"
#define STR_AUCTION_JOIN_ERROR      "放入物品錯誤"
#define STR_AUCTION_CHECK_ERROR     "查看物品錯誤"
#define STR_SHOUT_PRICE_SELF_ERR    "自己的物品不能參加拍賣"
#define STR_AUCTION_NOT_ITEM        "當前沒有物品拍賣"
#define STR_AUCTION_MIN_VALUE       "拍賣物品的底價不能少於%d枚金幣。"
#define STR_SPECIAL_GOODS_JOIN_ERR  "物品不能拍賣"		//"特殊物品不能拍賣"
#define STR_AUCTION_SHOUTPRICE_LOW  "你出的價必須高於現在的最低出價！！"
#define STR_AUCTION_BIDED           "您競拍的物品已流拍或被人買走。"
#define STR_AUCTION_BID_ERROR       "系統拍賣出錯"
#define STR_AUCTION_BID_FAIL        "拍賣物品失敗，物品已放入拍賣倉庫"
#define STR_AUCTION_BID             "%s，%s開價%d枚金幣，第%d次，還有沒有人開價?"
#define STR_AUCTION_BID_SUCCESS     "你的物品已經拍賣出去，獲得金錢:%d"
#define STR_AUCTION_SYS_JOIN_MORETIMES  "在同一時間裡開始多次系統拍賣"
#define STR_AUCTION_HAMMER          "恭喜 %s 以 %d 枚金幣買到 %s。"
#define STR_AUCTION_NEW             "本輪拍賣物品為%s的%s，底價為%d枚金幣，現在開始競拍。"
#define STR_AUCTION_SYS_ITEM_INVALID "系統拍賣[%u]中發現非法的itemtype值[%u]"
#define STR_EUDEMON_DEAD			"錯誤：幻獸已死亡。"
#define STR_TOOMUCH_MONEY_SAVED		"倉庫錢太多了，不可以再存。"
#define STR_TOOMUCH_MONEY			"您身上錢太多了，不可以再拾取。"
#define STR_TOOMUCH_MONEY_TO_DRAW	"您身上錢太多了，不可以再取。"
#define STR_NOT_ENOUGH_POTENTIAL	"您的潛能值不足，無法使用結界。"
#define STR_BOOTH_FULL				"您的攤位已滿，不能再放置更多物品。"
#define STR_TUTOR_LOGIN				"您的師傅%s來到了【魔域】。"
#define STR_TUTOR_LOGOUT			"您的師傅%s離開了【魔域】。"
#define STR_DROP_MONEY_SUCC			"您丟棄了%d金幣。"
#define STR_DIE_DROP_MONEY			"你遺失了%d枚金幣。"
#define STR_TEAM_MAGIC				"%s 發動。"
#define STR_TEAM_MAGIC2				"%s 發動，效果增加%d%%。"
#define STR_TEAM_STATUS_POWER_INC	"結界效果增加%d%%。"
#define STR_TEAM_STATUS_POWER_DEC	"結界效果降低%d%%。"
#define STR_TEAM_STATUS_DISAPPEAR	"結界效果消失。"
#define STR_INCPK_REDNAME_PUNISH	"PK值繼續增加，將會受到紅名的懲罰。"
#define STR_INCPK_BLACKNAME_PUNISH	"PK值繼續增加，將會受到黑名的懲罰。"
#define STR_INCPK_BLACKNAME_PUNISH2	"PK值繼續增加，將會延長黑名懲罰的時間。"
#define STR_NOT_FOR_TASK_PRIZE		"錯誤：不能作為傭兵任務獎勵物品。"
#define STR_EUDEMON_OVERLEVEL		"幻獸等級太高，您暫時無法召喚。"
#define STR_MAX_EUDEMONAMOUNT		"您最多只能同時召喚 %d 只幻獸。"
#define STR_EUDEMON_CHGNAME_OK		"幻獸改名操作成功。您將幻獸 %s 賦予了新名字 %s。"

#define STR_SYNWAR_ANNOUNCE			"%d-%d-%d 20:00:00 開始攻打幫派 %s。"
#define STR_SYNWAR_ANNOUNCE2		"%d-%d-%d 20:00:00 %s 幫派開始攻打本幫派。"

#define STR_EUDEMON_LEARNMAGIC_ERR_LEVEL	"閣下的幻獸等級太低，不足以學習此技能。"
#define STR_EUDEMON_LEARNMAGIC_ERR_TYPE		"閣下的幻獸不能學習此類型技能。"
#define STR_EUDEMON_LEARNMAGIC_ERR_DEAD		"閣下的幻獸已經死亡，無法學習。"
#define STR_EUDEMON_LEARNMAGIC_ERR_AGAIN	"閣下的幻獸已經學過此技能了。"

#define	STR_KICKOUT_MEMBER_ss		"%s被開除出了%s軍團。"


//cn_ddres.h 刪除部分
#define	STR_WEAPON_SKILL_UPLEV		"恭喜閣下武器熟練度又升一級。"
#define DRAGON_BALL_DROP			"寶光一閃，%s從怪物身上打出一個龍珠。"
#define	STR_SUPERMAN_BROADCAST_sddd	"%s 武藝精湛，在爆發時間內殺死%d隻怪物，榮登KO排行榜的第%d名，獎勵KO時間%d秒。"
#define	STR_DISPATCHXP_s			"%s 一聲怒吼，同隊的戰友個個精神一震，XP值上升！"
#define	STR_NO_ENOUGH_POWER			"閣下的內力不足，不能千里傳音!"
#define	STR_NO_ENOUGH_LEVEL			"閣下的修行太低，不能千里傳音!"
#define	STR_CAN_NOT_TALK			"您被點穴了，無法說話!"
#define	STR_DIE_FORGIVE	            "人死如燈滅，何苦糾纏不休？"
#define	STR_DIE_STOP_ATTACK	        "死者為大，禁止鞭屍。"
#define	STR_NO_MANA_UNLOCK		    "內力不足，不能衝穴!"
#define	STR_NO_CULTIVATION		    "閣下修為太淺，衝穴失敗!"
#define	STR_NO_PK_VILLAGE	        "旯揭蔬綬ㄛ寞撻祥腕祥植"
#define	STR_VITAL_POINT_STRICKEN	"您被點穴了，無法說話!"
#define	STR_NO_LV_BROADCAST	        "閣下的修行太低，不能千里傳音!"
#define	STR_NO_MANA_BROADCAST	    "閣下的內力不足，不能千里傳音!"
//---------------------------------------------------------------------------
#endif