///////////////////////////////////////////////////////////
//
//		CMsgUserAttrib.h
//

#ifndef		_MSGUSERSTATUS_H_
#define		_MSGUSERSTATUS_H_

#include "NetMsg.h"


// 取消32位的掩码限制
//const _MAX_MSGATRRIB	=32;			// ★：由于取数值属性时使用32位整数作为DIRTY掩码，故该值不能超过32。

enum {
		_USERATTRIB_NONE = -1,
		_USERATTRIB_SIZEADD,
		_USERATTRIB_ENERGY,
		_USERATTRIB_SOUL,
		_USERATTRIB_HEALTH,
		_USERATTRIB_FORCE,
		_USERATTRIB_SPEED,						// 速度 -- 客户端用的，与敏捷没有任何关系
		_USERATTRIB_NOBILITYRANK,	// 爵位
		_USERATTRIB_POSE,	
		_USERATTRIB_PROFFER,
		_USERATTRIB_LENGTH,						// zlong 2004-02-03
		_USERATTRIB_SUPERMAP_ORDER,

		_USERATTRIB_MERCENARYRANK,				// 佣兵等级
		_USERATTRIB_KEEPEFFECT,	// 低32位的魔法状态
		_USERATTRIB_HAIR,
		_USERATTRIB_MERCENARYEXP,	// 佣兵经验
		_USERATTRIB_FAT,	// zlong 2004-02-03
		_USERATTRIB_TUTOR_EXP,	// 导师等级
		_USERATTRIB_TUTOR_LEVEL			= 33,	// 导师经验
		_USERATTRIB_DEX	,	// 敏捷
		_USERATTRIB_POTENTIAL,	// 潜能
		_USERATTRIB_KEEPEFFECT2,	// 高32位的魔法状态
		_USERATTRIB_MAXENERGY,	// 最大体力
		_USERATTRIB_ARMORTYPE,	// 帮派成员时，改变玩家的身体的颜色
		_USERATTRIB_MAXEUDEMON,	// 最大可召唤幻兽数
		_USERATTRIB_MAXLIFEPERCENT,	// 受伤度
		_USERATTRIB_EUDBROODPACKSIZE,	// 玩家身上的幻兽孵化器尺寸

		_USERATTRIB_DIAMOND,	//玩家身上的钻石数
		_USERATTRIB_DIAMONDSAVED,	//玩家银行的钻石数

		_USERATTRIB_WEAPONR_CHGEXP,	//玩家手持武器经验值改变,因为数据量小，直接用这个发,不用MsgItemInfo.
		_USERATTRIB_SPIRIT_PERCENT,	//魂百分比
		_USERATTRIB_SPIRITGRID_NUM,	//当前魂格数量
		_USERATTRIB_SPIRITGRID_MAXNUM,	//当前最大魂格数量
		_USERATTRIB_HIDESTATUS,	//是否隐身
		_USERATTRIB_HONOR,	//20070210修罗:荣誉
		_USERATTRIB_HONOR_RANK,	//20070210修罗:荣誉军阶
		_USERATTRIB_HONOR_AWARD,	//20070210修罗:仅用来头顶显示
		_USERATTRIB_KILL_GOOD,	//20070213修罗:荣誉击杀次数
		_USERATTRIB_KILL_BAD,	//20070213修罗:非荣誉击杀次数
		_USERATTRIB_PACKCOUNT,	//20070213修罗:非荣誉击杀次数
		_USERATTRIB_STORAGELIMIT,	//20070213修罗:非荣誉击杀次数

		_USERATTRIB_SECONDEFFECTLOW32,	//特效2 低32位
		_USERATTRIB_SECONDEFFECTHIG32,	//特效2 高32位
		_USERATTRIB_SETEXP,// 陈剑飞添加 [6/16/2007]

		_USEREXIT_ALLTIME, // 下线泡点全部时间单位分钟 [9/15/2007 %PENGFENG%]

		_USERATTRIB_LOVELINESS, // 魅力 pengfeng

		_USERATTRIB_SETEXP2,	//  [11/14/2007 朱斌]	经验高32位
		_USERATTRIB_WEAPONR_CHGEXP2,	//  [11/15/2007 朱斌]
		_USERATTRIB_CURRENTSOUL,	//当前魂值
		_USERATTRIB_MAXSOUL,	//最大魂值

		_USERATTRIB_GIFT_ADD_FORCE,
		_USERATTRIB_GIFT_ADD_DEX,
		_USERATTRIB_GIFT_ADD_SOUL,
		_USERATTRIB_GIFT_ADD_HEALTH,
		_USERATTRIB_GIFT_ADD_LOVELINESS,	

		_USERATTRIB_GIFT_GIFTPOINT,	//天赋点
		_USERATTRIB_PACK_OPENEDROW,   //开放的背包总排数08.9.26独孤求败
		_USERATTRIB_EXP2,   //  	经验高32位

			

		_USERATTRIB_STONELEV,   //石头矿
		_USERATTRIB_GRASSLEV,   //伐木
		_USERATTRIB_BODYLEV,   //皮脂
		_USERATTRIB_BOXLEV,   //开宝箱
		
		_USERATTRIB_USETITLE,   //[游途道标 2008/10/14]使用称号状态

		_USERATTRIB_STOCKNUM,	//玩家股票数量

		_USERATTRIB_CITYWARE_ATTACKDEFENCE, //user 城战攻守标志
		_USERATTRIB_AUTOFIGHT,   //自动打怪标志
		_USERATTRIB_CITYWARE_DOMAIN, //城战占领id
		_USERATTRIB_UPLEVEL_TIME,//20090612haocq升级时间

		
		_USERATTRIB_FISH_TIRED,   //钓鱼疲劳度

		_USERATTRIB_MONSTER_SPEEDDOWN,  //怪物减速度

		_USERATTRIB_STRENG_Level,//--强化等级20091217陈志

		_USERATTRIB_AWARDITEM_TIME,//---赠送物品时间------
		_USERATTRIB_GIFT_ADD_hp,  // hp
		_USERATTRIB_GIFT_ADD_mp,  // MP
		_USERATTRIB_GIFT_ADD_crihit,//致命一击
		_USERATTRIB_GIFT_ADD_phyatt,//物理攻击
		_USERATTRIB_GIFT_ADD_magatt,//魔法攻击
		_USERATTRIB_GIFT_ADD_phydef,//物理防御
		_USERATTRIB_GIFT_ADD_magdef,//魔法防御
		_USERATTRIB_GIFT_ADD_hit,//命中
		_USERATTRIB_GIFT_ADD_dodge,//闪避
		_USERATTRIB_BUFF_ADD_STR,
		_USERATTRIB_BUFF_ADD_INT,
		_USERATTRIB_BUFF_ADD_STA,
		_USERATTRIB_BUFF_ADD_SPI,
		_USERATTRIB_BUFF_ADD_AGI,


		//基本		
		_USERATTRIB_MONEY				= 100,
		_USERATTRIB_MONEY2,
		_USERATTRIB_MONEY3,
		_USERATTRIB_MONEY4,
		_USERATTRIB_MONEY5,
		_USERATTRIB_MONEYSAVED,
		_USERATTRIB_PK,	
		_USERATTRIB_LEV,

		_USERATTRIB_EXP,
		_USERATTRIB_ADDPOINT,
		_USERATTRIB_LOOKFACE,
		_USERATTRIB_PORFESSION,
		_USERATTRIB_LIFE,
		_USERATTRIB_MANA,
		_USERATTRIB_SP,
		_USERATTRIB_MAXLIFE,		
		_USERATTRIB_MAXMANA,		
		_USERATTRIB_MAXSP,
		_USERATTRIB_PHYATT,
		_USERATTRIB_MAGATT,
		_USERATTRIB_PHYDEF,
		_USERATTRIB_MAGDEF,
		_USERATTRIB_HIT,
		_USERATTRIB_DODGE,
		_USERATTRIB_CRIT,
		_USERATTRIB_TOUGHT,
		_USERATTRIB_STR,
		_USERATTRIB_INT,
		_USERATTRIB_STA,
		_USERATTRIB_SPI,
		_USERATTRIB_AGI,

		_USERATTRIB_EXP_SEC,
		_USERATTRIB_ADDPOINT_SEC,
		_USERATTRIB_LOOKFACE_SEC,
		_USERATTRIB_PORFESSION_SEC,
		_USERATTRIB_LIFE_SEC,
		_USERATTRIB_MANA_SEC,
		_USERATTRIB_SP_SEC,
		_USERATTRIB_MAXLIFE_SEC,		
		_USERATTRIB_MAXMANA_SEC,		
		_USERATTRIB_MAXSP_SEC,
		_USERATTRIB_PHYATT_SEC,
		_USERATTRIB_MAGATT_SEC,
		_USERATTRIB_PHYDEF_SEC,
		_USERATTRIB_MAGDEF_SEC,
		_USERATTRIB_HIT_SEC,
		_USERATTRIB_DODGE_SEC,
		_USERATTRIB_CRIT_SEC,
		_USERATTRIB_TOUGHT_SEC,
		_USERATTRIB_STR_SEC,
		_USERATTRIB_INT_SEC,
		_USERATTRIB_STA_SEC,
		_USERATTRIB_SPI_SEC,
		_USERATTRIB_AGI_SEC,
		//影响
		_USERATTRIB_ADD_MAXLIFE,		
		_USERATTRIB_ADD_MAXMANA,		
		_USERATTRIB_ADD_MAXSP,
		_USERATTRIB_ADD_PHYATT,
		_USERATTRIB_ADD_MAGATT,
		_USERATTRIB_ADD_PHYDEF,
		_USERATTRIB_ADD_MAGDEF,
		_USERATTRIB_ADD_HIT,
		_USERATTRIB_ADD_DODGE,
		_USERATTRIB_ADD_CRIT,
		_USERATTRIB_ADD_TOUGHT,
		_USERATTRIB_ADD_STR,
		_USERATTRIB_ADD_INT,
		_USERATTRIB_ADD_STA,
		_USERATTRIB_ADD_SPI,
		_USERATTRIB_ADD_AGI,

		_USERATTRIB_FIRJOBLEV,
		_USERATTRIB_SECJOBLEV,
		_USERATTRIB_WARSOOCE,
		_USERATTRIB_PACKAGELEV,	

		_USERATTRIB_MASKLOW,
		_USERATTRIB_MASKHI,
		_USERATTRIB_DAYMASKLOW,
		_USERATTRIB_DAYMASKHI,
		_USERATTRIB_BANKLEV		=	180,//180 仓库等级


		_USERATTRIB_ADD_ATT1,
		_USERATTRIB_ADD_ATT2,
		_USERATTRIB_ADD_ATT3,
		_USERATTRIB_ADD_ATT4,
		_USERATTRIB_ADD_DEF1,
		_USERATTRIB_ADD_DEF2,
		_USERATTRIB_ADD_DEF3,
		_USERATTRIB_ADD_DEF4,

		_USERATTRIB_FEEL_SWITH,
		_USERATTRIB_CURJOB,
		//[2010-08-27 goto]//特殊大红大蓝
		_USERATTRIB_DRUG_ADDHP,
		_USERATTRIB_DRUG_ADDMP,
		_USERATTRIB_DRUG_ADDPET,
		_USERATTRIB_VIT,
		_USERATTRIB_NEWGIVEMASKLOW,
		_USERATTRIB_CREATEROLETIME,
		_USERATTRIB_JOINSYNTIME,
		_USERATTRIB_ENE,
		//添加用于玩家人物其他信息消息常量,没用到的预留
        _USERATTRIB_UserInfo_Feel  =200,    //心情
        _USERATTRIB_UserInfo_Tittle,         //称号
        _USERATTRIB_UserInfo_Syn ,           //帮派
        _USERATTRIB_UserInfo_Tutor,          //师傅
		_USERATTRIB_UserInfo_Mate,           //配偶
	    _USERATTRIB_UserInfo_MarryDate,       //成亲日期
		_USERATTRIB_UserInfo_Kill,            //杀气度
		_USERATTRIB_UserInfo_VipRank,          //vip等级
	    _USERATTRIB_UserInfo_BagRank,          //背包等级
		_USERATTRIB_UserInfo_WULIN ,           //武林同盟
	    _USERATTRIB_UserInfo_XIAYIZHI,         //侠义值
		_USERATTRIB_UserInfo_RONGYUZHI,        //荣誉值
	    _USERATTRIB_UserInfo_SynCon,           //帮派贡献
	    _USERATTRIB_UserInfo_AnswerData ,       //传道解惑值
	    _USERATTRIB_UserInfo_MajorCon ,        //主门派贡献
		_USERATTRIB_UserInfo_AssistCon,        //副门派贡献
	    _USERATTRIB_UserInfo_FrozenDoubleTime,   //冻结双倍时间
	    _USERATTRIB_UserInfo_VipLeft,            //vip剩余时间
	    _USERATTRIB_UserInfo_MateriaBagRank,    //材料包等级
	    _USERATTRIB_UserInfo_Activity,          //活跃度
		_USERATTRIB_UserOnLine_Award,
		_USERATTRIB_UserInfo_IsDress,			//是否显示时装
		_USERATTRIB_NEWGIVEMASKLOW2,
		_USERATTRIB_DAYMASKLOW2	,
		_USERATTRIB_DAYMASKHI2,
		_USERATTRIB_UserInfo_MonsterKill,				//杀怪个数
		_USERATTRIB_UserInfo_JimeiValue,
		_USERATTRIB_WARGAME_CAMP,		//竞技场阵营
		_USERATTRIB_ARENA_SCORE,//竞技场积分
		_USERATTRIB_EUDEMON_VIEW,//附体的特效
};

typedef struct 
{
	DWORD	ucAttributeType;
	DWORD	dwAttributeData;
}UserAttribStruct;


class CMsgUserAttrib : public CNetMsg
{
public:
	CMsgUserAttrib();
	virtual ~CMsgUserAttrib();

public:		//接口函数
//	BOOL	Create(OBJID idUser, int nType, DWORD dwData);
	BOOL	Create(OBJID idUser, int nType, __int64 i64Data);

//	BOOL	Append(int nType, DWORD dwData);
	BOOL	Append(int nType, __int64 i64Data);

public:
	BOOL			Create		(char* pMsgBuf, DWORD dwSize);
	void			Process		(CGameSocket* pSocket);

private:
	typedef struct
	{
		MSGHEAD_DEFINE

		OBJID				idUser;
		DWORD				dwAttributeNum;
		UserAttribStruct	setUserAttrib[1];			// 变长
	}MSG_Info;
	
	MSG_Info*	m_pInfo;
};

#endif
